In [33]:
import numpy as np

In [34]:

arr = np.array([[1,2,3,5],[4,5,6,7],[7,8,9,11],[11,12,13,15]])
arr
 

array([[ 1,  2,  3,  5],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 11],
       [11, 12, 13, 15]])

In [16]:
newarr1 = np.insert(arr,0,[[100,200,300,400]],axis=0)
newarr1

array([[100, 200, 300, 400],
       [  1,   2,   3,   5],
       [  4,   5,   6,   7],
       [  7,   8,   9,  11],
       [ 11,  12,  13,  15]])

In [22]:
newarr2 = np.insert(arr,0,[[100,200,300,400]],axis=1)
newarr2

array([[100,   1,   2,   3,   5],
       [200,   4,   5,   6,   7],
       [300,   7,   8,   9,  11],
       [400,  11,  12,  13,  15]])

In [29]:
newarr3 = np.append(arr,[[100,200,300,400]],axis=0)
newarr3

array([[  1,   2,   3,   5],
       [  4,   5,   6,   7],
       [  7,   8,   9,  11],
       [ 11,  12,  13,  15],
       [100, 200, 300, 400]])

In [35]:
arr[0,0]

1

In [37]:
len(arr)
    
        

4

In [46]:
def accessElement(array,rowIndex,colIndex):
    if rowIndex >= len(arr):
        print('no such item')
    elif colIndex >= len(arr):
        print('no such item')
    elif colIndex >= len(arr) and rowIndex >= len(arr):
        print('no such item')
    else:
        print('item is ',arr[rowIndex,colIndex])
    return

accessElement(arr,1,1)

item is  5


In [47]:
sum(arr)
# summing column wise

array([23, 27, 31, 38])

In [55]:
#nditer()
for i in np.nditer(arr):
    print(i)

1
2
3
5
4
5
6
7
7
8
9
11
11
12
13
15


In [56]:
for i in arr:
    print(i)

[1 2 3 5]
[4 5 6 7]
[ 7  8  9 11]
[11 12 13 15]


In [57]:
for i in arr:
    for k in i:
        print(k)
        

1
2
3
5
4
5
6
7
7
8
9
11
11
12
13
15


In [66]:
def traversring(array):
    for i in array:
        for k in i:
            print(k)
            
    return

traversring(arr)

1
2
3
5
4
5
6
7
7
8
9
11
11
12
13
15


In [128]:
def search(array,value):

    for i in range(len(array)):
        
        for j in range(len(array[i])):
            if array[i][j] == value:
                print('item {}'.format(value),'found at ({},{}) position'.format(i,j))
                
                return
    
    print('item {}'.format(value),'not found')
                
            
  

search(arr,12)

item 12 found at (3,1) position


In [140]:
arr

array([[ 1,  2,  3,  5],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 11],
       [11, 12, 13, 15]])

In [139]:
deleted_after_arr = np.delete(arr,0,axis=0)
deleted_after_arr

array([[ 4,  5,  6,  7],
       [ 7,  8,  9, 11],
       [11, 12, 13, 15]])

In [138]:
deleted_after_arr = np.delete(arr,1,axis=0)
deleted_after_arr

array([[ 1,  2,  3,  5],
       [ 7,  8,  9, 11],
       [11, 12, 13, 15]])

In [141]:
deleted_after_arr = np.delete(arr,0,axis=1)
deleted_after_arr

array([[ 2,  3,  5],
       [ 5,  6,  7],
       [ 8,  9, 11],
       [12, 13, 15]])

In [142]:
deleted_after_arr = np.delete(arr,1,axis=1)
deleted_after_arr

array([[ 1,  3,  5],
       [ 4,  6,  7],
       [ 7,  9, 11],
       [11, 13, 15]])